services:
  db:
    env_file: .env
    image: mariadb:12.1.2-ubi
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  php-fpm:
    build:
      context: ./php-fpm
    image: php-8.3-fpm-moodle:latest
    pull_policy: never
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./volumes/moodle:/var/www/html
      - ./volumes/moodledata:/var/local/moodledata
      - ./volumes/php-fpm/php.ini:/usr/local/etc/php-fpm/php.ini
    depends_on:
      - db

  nginx:
    #image: nginx:1.25-alpine
    image: nginx:stable-alpine3.23
    container_name: nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./volumes/moodle:/var/www/html
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
